channels:
  - conda-forge
dependencies:
  - mamba
  - python=3.11
  - numpy=1.26  # basics
  - scipy=1.11
  - xarray=2023.10
  - pandas=2.1
  - jupyterlab
  - matplotlib=3.8  # plotting
  - seaborn=0.13
  - scikit-learn=1.3 # ML
  - flaml=2.1
  - keras=3
  - tensorboard=2.15
  - pytorch=2.1
  - lightning=2.1
  - dask=2023.10  # utils
  - joblib=1.3
  - rasterio
